---
- name: Config leaf01 and leaf02 for lab4b
  hosts: switches
  become: yes
  tasks:
  - name: delete config
    nclu:
      commands:
      - del all
      commit: true

  - name: Setup ntp server
    nclu:
      commands:
      - add time ntp server 192.168.0.254 iburst
      - del time ntp server 0.cumulusnetworks.pool.ntp.org
      - del time ntp server 1.cumulusnetworks.pool.ntp.org
      - del time ntp server 2.cumulusnetworks.pool.ntp.org
      - del time ntp server 3.cumulusnetworks.pool.ntp.org
      atomic: true

- name: Configure CLAG on Leaf01 and Leaf02 Switches
  hosts: leaf01:leaf02
  become: yes
  vars:
    devices:
        leaf01:
            clag_role: "primary"
            clag_mac: "44:38:39:FF:00:01"
            clag_backupip: "192.168.0.12"
            VLANS:
                - vlan: "10"
                  vrrip: "10.0.10.1/24"
                  vrrmac: "00:00:00:00:1a:10"
                  bond: "SERVER01"
                  interface: "swp1"
                  realip: "10.0.10.2/24"
                - vlan: "20"
                  vrrip: "10.0.20.1/24"
                  vrrmac: "00:00:00:00:1a:20"
                  bond: "SERVER02"
                  interface: "swp2"
                  realip: "10.0.20.2/24"
        leaf02:
            clag_role: "secondary"
            clag_mac: "44:38:39:FF:00:01"
            clag_backupip: "192.168.0.11"
            VLANS:
                - vlan: "10"
                  vrrip: "10.0.10.1/24"
                  vrrmac: "00:00:00:00:1a:10"
                  bond: "SERVER01"
                  interface: "swp1"
                  realip: "10.0.10.3/24"
                - vlan: "20"
                  vrrip: "10.0.20.1/24"
                  vrrmac: "00:00:00:00:1a:20"
                  bond: "SERVER02"
                  interface: "swp2"
                  realip: "10.0.20.3/24"

  tasks:
  - name: Lab 4b -- Deploy configuration
    nclu:
        commit: true
        description: "Deploy Lab4b interface configuration"
        commands:
            - add clag peer sys-mac {{ devices[ansible_hostname].clag_mac }} interface swp49-50 {{ devices[ansible_hostname].clag_role }} backup-ip {{ devices[ansible_hostname].clag_backupip }}
            - add clag port bond {{ devices[ansible_hostname].VLANS[0].bond}} interface {{ devices[ansible_hostname].VLANS[0].interface }} clag-id 1
            - add clag port bond {{ devices[ansible_hostname].VLANS[1].bond}} interface {{ devices[ansible_hostname].VLANS[1].interface }} clag-id 2
            - add bond {{ devices[ansible_hostname].VLANS[0].bond }} bridge access  {{ devices[ansible_hostname].VLANS[0].vlan }}
            - add bond {{ devices[ansible_hostname].VLANS[1].bond }} bridge access  {{ devices[ansible_hostname].VLANS[1].vlan }}
            - add vlan {{ devices[ansible_hostname].VLANS[0].vlan }} ip address {{ devices[ansible_hostname].VLANS[0].realip }}
            - add vlan {{ devices[ansible_hostname].VLANS[1].vlan }} ip address {{ devices[ansible_hostname].VLANS[1].realip }}
            - add vlan {{ devices[ansible_hostname].VLANS[0].vlan }} ip address-virtual {{ devices[ansible_hostname].VLANS[0].vrrmac }} {{ devices[ansible_hostname].VLANS[0].vrrip }}
            - add vlan {{ devices[ansible_hostname].VLANS[1].vlan }} ip address-virtual {{ devices[ansible_hostname].VLANS[1].vrrmac }} {{ devices[ansible_hostname].VLANS[1].vrrip }}

  - name: show configuration
    shell: "net show configuration"
    register: output2

  - name: Print show config
    debug:
      var: output2