- name: Wipe Configuration
  hosts: spine,leaf
  become: yes
  roles:
  - reset

- name: Lab 1 Setup PTM
  hosts: leaf01,leaf02,spine01
  become: yes
  tasks:
  - name: Download the topology.dot file from the OOB-MGMT-SERVER
    get_url:
      url: http://192.168.0.254/topology.dot
      dest: /etc/ptm.d/topology.dot
      mode: 0755

  - name: Restart PTM Daemon to Apply new Topology.dot file
    service: name=ptmd state=restarted

  - name: Test PTM
    shell: ptmctl
    register: ptm_output
    failed_when: ('pass' not in ptm_output.stdout)

  - name: Install License
    shell: cl-license -i http://192.168.0.254/license.lic
    register: cllicense_output
    failed_when: ('License file installed.' not in cllicense_output.stdout)


- name: Configure CLAG on Leaf01 and Leaf02 Switches
  hosts: leaf01:leaf02
  become: yes
  vars:
    devices:
        leaf01:
            clag_role: "primary"
            clag_mac: "44:38:39:FF:00:01"
            clag_backupip: "192.168.0.12"
            VLANS:
                - vlan: "10"
                  vrrip: "10.0.10.1/24"
                  vrrmac: "00:00:00:00:1a:10"
                  bond: "SERVER01"
                  interface: "swp1"
                  realip: "10.0.10.2/24"
                - vlan: "20"
                  vrrip: "10.0.20.1/24"
                  vrrmac: "00:00:00:00:1a:20"
                  bond: "SERVER02"
                  interface: "swp2"
                  realip: "10.0.20.2/24"
        leaf02:
            clag_role: "secondary"
            clag_mac: "44:38:39:FF:00:01"
            clag_backupip: "192.168.0.11"
            VLANS:
                - vlan: "10"
                  vrrip: "10.0.10.1/24"
                  vrrmac: "00:00:00:00:1a:10"
                  bond: "SERVER01"
                  interface: "swp1"
                  realip: "10.0.10.3/24"
                - vlan: "20"
                  vrrip: "10.0.20.1/24"
                  vrrmac: "00:00:00:00:1a:20"
                  bond: "SERVER02"
                  interface: "swp2"
                  realip: "10.0.20.3/24"

  tasks:
  - name: Lab 4b -- Deploy configuration
    nclu:
        commit: true
        description: "Deploy Lab4b interface configuration"
        commands:
            - add clag peer sys-mac {{ devices[ansible_hostname].clag_mac }} interface swp49-50 {{ devices[ansible_hostname].clag_role }} backup-ip {{ devices[ansible_hostname].clag_backupip }}
            - add clag port bond {{ devices[ansible_hostname].VLANS[0].bond}} interface {{ devices[ansible_hostname].VLANS[0].interface }} clag-id 1
            - add clag port bond {{ devices[ansible_hostname].VLANS[1].bond}} interface {{ devices[ansible_hostname].VLANS[1].interface }} clag-id 2
            - add bond {{ devices[ansible_hostname].VLANS[0].bond }} bridge access  {{ devices[ansible_hostname].VLANS[0].vlan }}
            - add bond {{ devices[ansible_hostname].VLANS[1].bond }} bridge access  {{ devices[ansible_hostname].VLANS[1].vlan }}
            - add vlan {{ devices[ansible_hostname].VLANS[0].vlan }} ip address {{ devices[ansible_hostname].VLANS[0].realip }}
            - add vlan {{ devices[ansible_hostname].VLANS[1].vlan }} ip address {{ devices[ansible_hostname].VLANS[1].realip }}
            - add vlan {{ devices[ansible_hostname].VLANS[0].vlan }} ip address-virtual {{ devices[ansible_hostname].VLANS[0].vrrmac }} {{ devices[ansible_hostname].VLANS[0].vrrip }}
            - add vlan {{ devices[ansible_hostname].VLANS[1].vlan }} ip address-virtual {{ devices[ansible_hostname].VLANS[1].vrrmac }} {{ devices[ansible_hostname].VLANS[1].vrrip }}

- name: Restart NetQ
  hosts: leaf01,leaf02,spine01
  become: yes
  tasks:
  - name: Restart the netq-agent
    service: name=netq-agent state=restarted

- name: Server Configuration
  hosts: server01,server02
  become: yes
  tasks:
  - name: Copy Interfaces Configuration File
    copy: src=./{{ ansible_hostname }}.cfg dest=/etc/network/interfaces

  - name: Restart Networking
    service: name=networking state=restarted
